name: Test-linstor-labelt
on:
  release:
    types: [published]
  pull_request:
    types: [labeled]
jobs:

  labels:
    name: if Label linstor
    if: github.event.label.name == 'linstor-test'
    runs-on: ubuntu-latest
    steps:
      - name: Print to console
        run: echo "linstor test run-2"